# Site settings
title: "JacobWilson.IO"
email: "startpage@nexak.com"
description: "Start Page"
baseurl: ""
url: "https://www.jacobwilson.io"
timezone: "America/New_York"

# Author
author:
  name: "Jacob"

# Weather
weather:
  latitude: 36.29417
  longitude: -82.47250
  unit: fahrenheit

# Build settings
plugins:
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
